name: 'Xcode Sigin'
description: 'Import Apple Code-signing Certificates and Provision Profile'
author: 'Tâm Võ'

branding:
  icon: 'archive'
  color: 'red'

inputs:
  BUILD_CERTIFICATE_BASE64:
    description: 'Apple signing certificate file'
    required: true
  BUILD_PROVISION_PROFILE_BASE64:
    description: 'Apple signing certificate profile'
    required: false
  P12_PASSWORD:
    description: 'Apple signing certificate password'
    required: true
  KEYCHAIN_PASSWORD:
    description: 'Keychain password'
    required: true

outputs:
  cache-hit:
    description: 'A boolean value to indicate if cache was found and restored'

runs:
  using: node20
  main: dist/index.js
  # post: dist/save/index.js
  # post-if: success()
