export enum Inputs {
  CERTIFICATE_BASE64 = 'BUILD_CERTIFICATE_BASE64',
  PROVISION_PROFILE_BASE64 = 'BUILD_PROVISION_PROFILE_BASE64',
  P12_PASSWORD = 'P12_PASSWORD',
  KEYCHAIN_PASSWORD = 'KEYCHAIN_PASSWORD'
}

export enum States {
  CERTIFICATE_BASE64 = 'CERTIFICATE_BASE64',
  CERTIFICATE_PATH = 'CERTIFICATE_PATH',
  PROVISION_PROFILE_BASE64 = 'PROVISION_PROFILE_BASE64',
  PROVISION_PROFILE_PATH = 'PROVISION_PROFILE_PATH',
  KEYCHAIN_PASSWORD = 'KEYCHAIN_PASSWORD',
  KEYCHAIN_PATH = 'KEYCHAIN_PATH',
  RUNNER_TEMP_PATH = 'RUNNER_TEMP_PATH',
  P12_PASSWORD = 'P12_PASSWORD'
}

export type StateMap = keyof typeof States
