export enum Inputs {
  CERTIFICATE_BASE64 = 'BUILD_CERTIFICATE_BASE64',
  PROVISION_PROFILE_BASE64 = 'BUILD_PROVISION_PROFILE_BASE64',
  P12_PASSWORD = 'P12_PASSWORD',
  KEYCHAIN_PASSWORD = 'KEYCHAIN_PASSWORD'
}
